#
# Experimental Travis-CI
#
# For now, the build matrix has a single member: linux-arm64
# Pinned on the oldest available distribution, to get a generic Linux build.

language: c

jobs:
  include:
    - os: linux
      dist: xenial
      arch: arm64
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode11.3

install: skip

script:
  - ./brink.sh detect_os
  - ./brink.sh deps
  - ./brink.sh test_ci
