#
# Experimental Travis CI.
#
# Linux ARM64 target is pinned on the oldest distribution available on Travis,
# to get a generic ARM64 Linux build.

language: minimal

jobs:
  include:
    - os: linux
      dist: xenial
      arch: arm64
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode11.3

install: skip

script:
  - ./brink.sh detect_os
  - ./brink.sh deps
  - ./brink.sh test_ci
