# Changes are disabled.
codecov:
  notify:
    after_n_builds: 1
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  status:
    patch:
      default:
        target: 100%
    project:
      default:
        target: auto
      tests:
        target: 100%
        flags: tests

flags:
  tests:
    paths:
      - tests/

comment:
  layout: "header, diff, files"
  behavior: default
