# Changes are disabled.
codecov:
  notify:
    after_n_builds: 1
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  status:
    patch:
      default:
        target: 100%
    project:
      default:
        target: auto
        threshold: 0.1%

comment:
  layout: "header, diff, files, components"
  behavior: default


component_management:
  # default rules that will be inherited by all components
  default_rules:
    statuses:
      - type: project
        target: 100%
        branches:
          - "!main"
  individual_components:
    - component_id: component_tests
      name: tests
      paths:
        - src/chevah_compat/tests/**
        - src/chevah_compat/testing/**
