# See ruff settings at https://docs.astral.sh/ruff/settings/
[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "build-py3",
    "dist",
    "node_modules",
    "site-packages",
]

# Same as Black.
line-length = 80
indent-width = 4

target-version = "py311"

[tool.ruff.lint]

select = [
    "F",
    "E", "W",
    "I",
    #"UP",
    #"YTT",
    "FLY",
    ]
ignore = [
    ]

external = [
    "cover",  # Our custom marker for coverage.
    ]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "lf"
docstring-code-format = false
docstring-code-line-length = "dynamic"
