# See ruff settings at https://docs.astral.sh/ruff/settings/
[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "build-py3",
    "dist",
    "node_modules",
    "site-packages",
]

# Same as Black.
line-length = 80
indent-width = 4

target-version = "py311"

[tool.ruff.lint]

# Still to enable
# ANN flake8-annotations
# ARG flake8-unused-arguments
# B flake8-bugbear
# C90 mccabe
# CPY flake8-copyright - needs preview features
# D pydocstyle
# DTZ flake8-datetimez - need to fix datetime usage
# G flake8-logging-format
# INT flake8-gettext
# N pep8-naming - poor support for interfaces
# PL Pylint
# PT flake8-pytest-style
# PTH flake8-use-pathlib
# Q flake8-quotes
# RET flake8-return
# S flake8-bandit
# SIM flake8-simplify
# SLF flake8-self - check private member access
# TCH flake8-type-checking
select = [
    "A",
    "AIR",
    "ASYNC",
    "BLE",
    "C4",
    "COM",
    "E", "W",
    "EXE",
    "ERA",
    "F",
    "FA",
    "FLY",
    "FURB",
    "I",
    "ICN",
    "INP",
    "ISC",
    "LOG",
    "PERF",
    "PGH",
    "PIE",
    "RET",
    "RUF",
    "PYI",
    "RSE",
    "SLOT",
    "T10",
    "T20",
    "TD",
    "TID",
    "TRY",
    "YTT",
    "UP",
    ]
ignore = [
    "BLE001",
    "COM812",
    "ISC001",
    # TODO: Update code to disable ruff rules.
    # https://github.com/chevah/compat/issues/701
    "RUF005",  # List concatenation
    "RUF012",  # Class mutable attributes
    "TRY003",
    "TD002",  # We don't use authors tag for todos.
    ]

external = [
    "cover",  # Our custom marker for coverage.
    ]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "lf"
docstring-code-format = false
docstring-code-line-length = "dynamic"
