#
# GitHub actions to test chevah-compat.
#
# Available VMs. Don't use `-latest` as we want to pin an OS version.
# https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
#
# When running a tmate debug session you might need to increase the
# timeout-minutes for each build.

name: Bare

on:
  push:
    branches: [ master ]
    paths:
    - '**.py'
  pull_request:
    branches: [ master ]
    paths:
    - '**.py'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  TMATE_DEBUG: 'no'


jobs:

  ubuntu-2004-unicode-path:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          build-py3
        key: ${{ runner.os }}-${{ hashFiles('pavement.py') }}-${{ hashFiles('pythia.conf') }}-unicode

    - name: Deps
      run: ./pythia.sh deps

    - uses: chevah/python-info-action@v1
      with:
        python-path: build-py3/bin/python

    - name: Move build to Unicode path
      run: mv build-py3 build-py3-ț

    - name: Test
      run: ./pythia.sh test_ci2
      env:
        CHEVAH_BUILD: build-py3-ț

    - name: Tmate debug on failure
      if: failure() && env.TMATE_DEBUG == 'yes'
      uses: chevah/action-tmate@v3
      with:
        limit-access-to-actor: true

    - name: Move build back to to ascii
      run: mv build-py3-ț build-py


  ubuntu-2204-ascii-path:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Fail on skip-ci
      if: ${{ github.event.after }}
      run: git log -1 --pretty=format:"%s" ${{ toJSON(github.event.after) }} | grep -v 'skip-ci'

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          build-py3
        key: ${{ runner.os }}-${{ hashFiles('pavement.py') }}-${{ hashFiles('pythia.conf') }}-ascii

    - name: Deps
      run: ./pythia.sh deps

    - name: Test
      run: ./pythia.sh test_ci2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Tmate debug on failure
      if: failure() && env.TMATE_DEBUG == 'yes'
      uses: chevah/action-tmate@v3
      with:
        limit-access-to-actor: true

    - name: Publish cov
      run: ./pythia.sh codecov_publish
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  macos-unicode-path:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ macos-11 ]
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          build-py3
        key: ${{ runner.os }}-${{ hashFiles('pavement.py') }}-${{ hashFiles('pythia.conf') }}-unicode

    - name: Deps
      run: ./pythia.sh deps

    - name: Move build to Unicode path
      run: mv build-py3 build-py3-ț

    - name: Test
      run: ./pythia.sh test_ci2
      env:
        CHEVAH_BUILD: build-py3-ț
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Tmate debug on failure
      if: failure() && env.TMATE_DEBUG == 'yes'
      uses: chevah/action-tmate@v3
      with:
        limit-access-to-actor: true

    - name: Move build back to to ascii
      run: mv build-py3-ț build-py3

    - name: Publish cov
      run: ./pythia.sh codecov_publish
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  macos-ascii-path:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ macos-12 ]
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          build-py3
        key: ${{ runner.os }}-${{ hashFiles('pavement.py') }}-${{ hashFiles('pythia.conf') }}-ascii

    - name: Deps
      run: ./pythia.sh deps

    - name: Test
      run: ./pythia.sh test_ci2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Tmate debug on failure
      if: failure() && env.TMATE_DEBUG == 'yes'
      uses: chevah/action-tmate@v3
      with:
        limit-access-to-actor: true

    - name: Publish cov
      run: ./pythia.sh codecov_publish
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  windows:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ 'windows-2019', 'windows-2022' ]
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v3

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          build-py3
        key: ${{ runner.os }}-${{ hashFiles('pavement.py') }}-${{ hashFiles('pythia.conf') }}

    - name: Deps
      run: |
        ./pythia.sh deps
        ./build-py3/lib/python.exe Scripts/pywin32_postinstall.py --install

    - name: Test
      run: ./pythia.sh test_ci2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Tmate debug on failure
      if: failure() && env.TMATE_DEBUG == 'yes'
      uses: chevah/action-tmate@v3
      with:
        limit-access-to-actor: true

    - name: Public coverage
      if: ${{ !cancelled() }}
      run: ./pythia.sh codecov_publish
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
