#
# GitHub actions to test chevah-compat under Docker.
#


name: Docker


on:
  push:
    branches: [ master ]
  pull_request:


concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true


env:
  CHEVAH_REPO: compat
  USER: chevah
  CHEVAH_CONTAINER: yes


jobs:

  standard:

    name: ${{ matrix.container }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - alpine:3.18
          - amazonlinux:2
          - amazonlinux:2022
          - centos:8.2.2004
          - centos-stream9-fips
          - oraclelinux:8
          - ubuntu:14.04
          - ubuntu:16.04
          - ubuntu:22.04

    # ubuntu-latest is GitHub's newest well-suported Linux distro.
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # On Alpine, OpenSSL must be updated to latest version for python-package.
    - name: Alpine setup
      if: startsWith(matrix.container, 'alpine')
      run: |
        apk upgrade -U
        apk add git bash shadow sudo curl

    - name: Amazon Linux 2022 setup
      if: matrix.container == 'amazonlinux:2022'
      run: yum -y install libxcrypt-compat

    - name: Yum-based setup
      if: startsWith(matrix.container, 'centos') || startsWith(matrix.container, 'amazon') || startsWith(matrix.container, 'oracle')
      run: yum -y install git tar which sudo

    - name: Ubuntu setup
      if: startsWith(matrix.container, 'ubuntu')
      run: |
        apt-get update
        apt-get dist-upgrade -y
        apt-get install -y git curl sudo

    # On a Docker container, everything runs as root by default.
    - name: Chevah user setup
      run: |
        useradd -g adm -s /bin/bash -m chevah
        echo '%adm    ALL=NOPASSWD: ALL' > /etc/sudoers

    # GHA's checkout action fails on CentOS 5/6, issue same commands manually.
    # This fails when opening a new PR, but works starting with second commit.
    - name: Clone sources independently
      run: |
        cd /home/chevah/
        git init $CHEVAH_REPO
        cd $CHEVAH_REPO
        # Cleanup the repo.
        git rev-parse --symbolic-full-name --verify --quiet HEAD || true
        git rev-parse --symbolic-full-name --branches || true
        git remote remove origin || true
        # Update repo token.
        git remote add origin https://github.com/chevah/$CHEVAH_REPO
        git fetch --no-tags --prune origin
        # Prepare the code.
        git clean -f
        git reset --hard ${{ github.event.after }}
        git log -1 --format='%H'

    # This action also fails on CentOS 5/6.
    - name: Cache build
      uses: actions/cache@v3
      if: matrix.container != 'proatria/centos:5.11-chevah1' && matrix.container != 'centos:6.10'
      with:
        path: |
          /home/chevah/$CHEVAH_REPO/build-$CHEVAH_REPO
        key: ${{ runner.os }}-${{ hashFiles('pavement.py') }}-${{ hashFiles('pythia.conf') }}-${{ matrix.container }}

    - name: Deps
      run: |
        cd /home/chevah/$CHEVAH_REPO
        ./pythia.sh deps
        chown -R chevah .

    - uses: chevah/python-info-action@v1
      with:
        python-path: /home/chevah/$CHEVAH_REPO/build-py3/bin/python

    - name: Build
      run: |
        cd /home/chevah/$CHEVAH_REPO
        su chevah -c "./pythia.sh build"

    - name: Test
      run: |
        cd /home/chevah/$CHEVAH_REPO
        su chevah -c "./pythia.sh test_ci2"

  # Helper so that on GitHub repo settings we can configure a single job as
  # required.
  docker-required:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: always()
    needs:
      - standard
    steps:
      - name: Require all successes
        shell: python3 {0}
        env:
          RESULTS: ${{ toJSON(needs.*.result) }}
        run: |
          import json
          import os
          import sys
          results = json.loads(os.environ["RESULTS"])
          sys.exit(0 if all(result == "success" for result in results) else 1)
