#
# GitHub actions to test chevah-compat under Docker.
#

name: GitHub-CI-Docker


on:
  push:
    branches: [ master ]
    paths:
    - '**.py'
  pull_request:
    branches: [ master ]
    paths:
    - '**.py'


concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true


env:
  CHEVAH_REPO: compat
  USER: chevah
  CHEVAH_CONTAINER: yes


jobs:

  standard:

    name: ${{ matrix.container }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - alpine:3.14
          - amazonlinux:2018.03
          - amazonlinux:2
          - centos:5.11
          - centos:6.10
          - centos:7
          - centos:8.2.2004
          - centos:8

    # ubuntu-latest is GitHub's newest well-suported Linux distro.
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # On Alpine, OpenSSL must be updated to latest version for python-package.
    - name: Alpine setup
      if: startsWith(matrix.container, 'alpine')
      run: |
        apk upgrade -U
        apk add git bash libffi shadow sudo curl

    # Final CentOS 5 version is used to build the generic Linux package.
    - name: CentOS 5.11 setup
      if: matrix.container == 'centos:5.11'
      run: |
        sed -i s/^mirrorlist=/#mirrorlist=/ /etc/yum.repos.d/*.repo
        sed -i s@^#baseurl=http://mirror.centos.org/centos/\$releasever/@baseurl=http://vault.centos.org/5.11/@ /etc/yum.repos.d/*.repo
        yum -y upgrade
        # Use https://bin.chevah.com:20443/third-party-stuff/centos5/tuxad/
        # when tuxad.de dissapears, it has the minimum required stuff.
        rpm -i http://www.tuxad.de/rpms/tuxad-release-5-1.noarch.rpm
        yum -y install wget curl gcc44 make m4 automake libtool patch sudo which openssh-clients
        ln -s /usr/bin/gcc44 /usr/local/bin/gcc
        wget --mirror --no-parent https://bin.chevah.com:20443/third-party-stuff/centos5/endpoint/
        cd bin.chevah.com\:20443/third-party-stuff/centos5/endpoint/
        rpm -i local-perl-*.rpm
        rpm -i --nodeps git{-core,}-2.5.0-1.ep.x86_64.rpm

    - name: CentOS 6.10 setup
      if: matrix.container == 'centos:6.10'
      run: |
        sed -i s/^mirrorlist=/#mirrorlist=/ /etc/yum.repos.d/*.repo
        sed -i s@^#baseurl=http://mirror.centos.org/centos/\$releasever/@baseurl=http://vault.centos.org/6.10/@ /etc/yum.repos.d/*.repo
        yum -y upgrade

    # OpenSSL got updated in 8.3 from 1.1.1c to 1.1.1g.
    - name: CentOS 8.2 setup
      if: matrix.container == 'centos:8.2.2004'
      run: |
        sed -i s/^mirrorlist=/#mirrorlist=/ /etc/yum.repos.d/*.repo
        sed -i s@^#baseurl=http://mirror.centos.org/\$contentdir/\$releasever/@baseurl=https://vault.centos.org/8.2.2004/@ /etc/yum.repos.d/*.repo
        yum -y upgrade

    - name: Yum-based setup
      if: startsWith(matrix.container, 'centos') || startsWith(matrix.container, 'amazon')
      run: yum -y install git tar which sudo

    # On a Docker container, everything runs as root by default.
    - name: Chevah user setup
      run: |
        useradd -g adm -s /bin/bash -m chevah
        echo '%adm    ALL=NOPASSWD: ALL' > /etc/sudoers

    # GHA's checkout action doesn't work on CentOS 5/6. This fails on opening a new PR.
    - name: Clone sources independently
      run: |
        cd /home/chevah/
        git init $CHEVAH_REPO
        cd $CHEVAH_REPO
        # Cleanup the repo.
        git rev-parse --symbolic-full-name --verify --quiet HEAD || true
        git rev-parse --symbolic-full-name --branches || true
        git remote remove origin || true
        # Update repo token.
        git remote add origin https://github.com/chevah/$CHEVAH_REPO
        git fetch --no-tags --prune origin
        # Prepare the code.
        git clean -f
        git reset --hard ${{ github.event.after }}
        git log -1 --format='%H'

    - name: Cache build
      uses: actions/cache@v2
      if: matrix.container != 'centos:5.11' && matrix.container != 'centos:6.10'
      with:
        path: |
          /home/chevah/$CHEVAH_REPO/build-$CHEVAH_REPO
        key: ${{ runner.os }}-${{ hashFiles('pavement.py') }}-${{ hashFiles('brink.conf') }}-${{ matrix.container }}

    - name: Deps
      run: |
        cd /home/chevah/$CHEVAH_REPO
        ./brink.sh deps
        chown -R chevah .

    - uses: twisted/python-info-action@v1
      with:
        python-path: /home/chevah/$CHEVAH_REPO/build-$CHEVAH_REPO/bin/python

    - name: Build
      run: |
        cd /home/chevah/$CHEVAH_REPO
        su chevah -c "./brink.sh build"

    - name: Test
      run: |
        cd /home/chevah/$CHEVAH_REPO
        su chevah -c "./brink.sh test_ci2"
