#
# GitHub actions to test chevah-compat.
#
# Available VMs. Don't use `-latest` as we want to pin an OS version.
# https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
#
# When running a tmate debug session you might need to increase the
# timeout-minutes for each build.
name: GitHub-CI

on:
  push:
    branches: [ master ]
    paths:
    - '**.py'
  pull_request:
    branches: [ master ]
    paths:
    - '**.py'


env:
  TMATE_DEBUG: 'no'


jobs:

  static-checks:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Show action context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump event data
      run: |
        cat  << EOF
        ${{ toJSON(github.event) }}
        EOF

    - uses: chevah/auto-cancel-redundant-job@v1
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Fail on skip-ci
      if: ${{ github.event.after }}
      run: git log -1 --pretty=format:"%s" ${{ toJSON(github.event.after) }} | grep -v 'skip-ci'

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          build-server/
        key: ${{ runner.os }}-${{ hashFiles('pavement.py') }}-${{ hashFiles('brink.conf') }}

    - name: Deps
      run: ./brink.sh deps

    - name: Test linters
      run: ./brink.sh lint --all


  ubuntu-2004-unicode-path:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Make sure we don't have multiple job
    - uses: chevah/auto-cancel-redundant-job@v1
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Fail on skip-ci
      if: ${{ github.event.after }}
      run: git log -1 --pretty=format:"%s" ${{ toJSON(github.event.after) }} | grep -v 'skip-ci'

    - name: Cache build
      uses: actions/cache@v2
      with:
        path: |
          build-compat
        key: ${{ runner.os }}-${{ hashFiles('pavement.py') }}-${{ hashFiles('brink.conf') }}-unicode

    - name: Deps
      run: ./brink.sh deps

    - name: Move build to Unicode path
      run: mv build-compat build-compat-ț

    - name: Test
      run: ./brink.sh test_ci2
      env:
        CHEVAH_BUILD: build-compat-ț

    - name: Tmate debug on failure
      if: failure() && env.TMATE_DEBUG == 'yes'
      uses: mxschmitt/action-tmate@v2

    - name: Move build back to to ascii
      run: mv build-compat-ț build-compat


  ubuntu-1804-ascii-path:
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Make sure we don't have multiple job
    - uses: chevah/auto-cancel-redundant-job@v1
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Fail on skip-ci
      if: ${{ github.event.after }}
      run: git log -1 --pretty=format:"%s" ${{ toJSON(github.event.after) }} | grep -v 'skip-ci'

    - name: Cache build
      uses: actions/cache@v2
      with:
        path: |
          build-compat
        key: ${{ runner.os }}-${{ hashFiles('pavement.py') }}-${{ hashFiles('brink.conf') }}-ascii

    - name: Deps
      run: ./brink.sh deps

    - name: Test
      run: ./brink.sh test_ci2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Tmate debug on failure
      if: failure() && env.TMATE_DEBUG == 'yes'
      uses: mxschmitt/action-tmate@v2

    - name: Publish cov
      run: ./brink.sh codecov_publish
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  osx-unicode-path:
    runs-on: macos-latest
    steps:
    - uses: chevah/auto-cancel-redundant-job@v1
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Fail on skip-ci
      if: ${{ github.event.after }}
      run: git log -1 --pretty=format:"%s" ${{ toJSON(github.event.after) }} | grep -v 'skip-ci'

    - name: Cache build
      uses: actions/cache@v2
      with:
        path: |
          build-compat
        key: ${{ runner.os }}-${{ hashFiles('pavement.py') }}-${{ hashFiles('brink.conf') }}

    - name: Deps
      run: ./brink.sh deps

    - name: Move build to Unicode path
      run: mv build-compat build-compat-ț

    - name: Test
      run: ./brink.sh test_ci2
      env:
        CHEVAH_BUILD: build-compat-ț
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Tmate debug on failure
      if: failure() && env.TMATE_DEBUG == 'yes'
      uses: mxschmitt/action-tmate@v2

    - name: Move build back to to ascii
      run: mv build-compat-ț build-compat

    - name: Publish cov
      run: ./brink.sh codecov_publish
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  windows:
    runs-on: windows-latest
    steps:
    - uses: chevah/auto-cancel-redundant-job@v1
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Fail on skip-ci
      run: git log -1 --pretty=format:"%s" ${{ toJSON(github.event.pull_request.head.sha) }} | grep -v 'skip-ci'

    - name: Cache build
      uses: actions/cache@v2
      with:
        path: |
          build-compat
        key: ${{ runner.os }}-${{ hashFiles('pavement.py') }}-${{ hashFiles('brink.conf') }}

    - name: Deps
      run: sh ./brink.sh deps

    - name: Test
      run: sh ./brink.sh test_ci2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Public coverage
      run: sh ./brink.sh codecov_publish
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
